<?php

namespace AppBundle\Repository;

/**
 * Light_NovelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Light_NovelRepository extends \Doctrine\ORM\EntityRepository
{
}
